schema_version: 20180708
name: fibonaccigo
version: 0.0.14
runtime: go
build_image: fnproject/go:1.15-dev
run_image: fnproject/go:1.15
entrypoint: ./func
triggers:
- name: fibonaccigo
  type: http
  source: /fibonaccigo
