schema_version: 20180708
name: fibonacci
version: 0.0.1
runtime: java11
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.145
run_image: fnproject/fn-java-fdk:jre11-1.0.145
cmd: com.oracle.graalvm.fn.FibonacciFunction::handleRequest
triggers:
- name: fibonacci
  type: http
  source: /fibonacci
